# Generated by Django 3.1.5 on 2021-04-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='case_number_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='classification',
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected', models.BooleanField()),
                ('infector', models.BooleanField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.case')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
            ],
        ),
    ]
