# Generated by Django 3.1.5 on 2021-05-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210426_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sse',
            field=models.BooleanField(default=False),
        ),
    ]
